# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2025.8.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: Example simulated camera for BL01T

entities:
  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: autosave.Autosave
    P: "BL01T-DI-CAM-01:"

  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: BL01T-DI-CAM-01
    R: ":DET:"
    # DATATYPE:0 = Int8 - TODO add an enum to the support yaml
    DATATYPE: 0
    WIDTH: 1024
    HEIGHT: 1024

  - type: epics.PostStartupCommand
    command: |
      dbpf BL01T-DI-CAM-01:DET:AcquireTime 0.1
      dbpf BL01T-DI-CAM-01:ARR:EnableCallbacks 1
      dbpf BL01T-DI-CAM-01:PROC:EnableCallbacks 1
      dbpf BL01T-DI-CAM-01:ROI:EnableCallbacks 1
      dbpf BL01T-DI-CAM-01:PVA:EnableCallbacks 1
      dbpf BL01T-DI-CAM-01:DET:Acquire 1

  # - type: ffmpegServer.ffmpegStream
  #   PORT: DET.MJP
  #   P: BL01T-DI-CAM-01
  #   R: ":MJP:"
  #   NDARRAY_PORT: DET.DET

  - type: ADCore.NDROI
    PORT: DET.ROI
    P: BL01T-DI-CAM-01
    R: ":ROI:"
    NDARRAY_PORT: DET.DET

  - type: ADCore.NDProcess
    PORT: DET.PROC
    P: BL01T-DI-CAM-01
    R: ":PROC:"
    NDARRAY_PORT: DET.ROI

  - type: ADCore.NDPvxsPlugin
    PORT: DET.PVA
    PVNAME: BL01T-DI-CAM-01:PVA:OUTPUT
    P: BL01T-DI-CAM-01
    R: ":PVA:"
    NDARRAY_PORT: DET.DET

  - type: ADCore.NDStdArrays
    PORT: DET.ARR
    P: BL01T-DI-CAM-01
    R: ":ARR:"
    NDARRAY_PORT: DET.PROC
    TYPE: Int8
    NELEMENTS: 1048576
    FTVL: UCHAR

  - type: ADCore.NDStats
    PORT: DET.STAT
    P: BL01T-DI-CAM-01
    R: ":STAT:"
    NDARRAY_PORT: DET.DET
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDFileHDF5
    PORT: DET.HDF
    P: BL01T-DI-CAM-01
    R: ":HDF5:"
    NDARRAY_PORT: DET.PROC

  - type: ADCore.NDFileTIFF
    PORT: DET.TIFF
    P: BL01T-DI-CAM-01
    R: ":TIFF:"
    NDARRAY_PORT: DET.PROC

  - type: ADCore.NDOverlay
    PORT: DET.OVER
    P: BL01T-EA-TST-02
    R: ":OVER:"
    NDARRAY_PORT: DET.PROC
    NOverlays: 4

  - type: ADCore.NDROIStat
    PORT: DET.ROISTAT
    P: BL01T-EA-TST-02
    R: ":ROISTAT:"
    NDARRAY_PORT: DET.PROC
    MAX_ROIS: 8

  - type: ADCore.NDFileNetCDF
    PORT: DET.CDF
    P: BL01T-DI-CAM-01
    R: ":NCDF:"
    NDARRAY_PORT: DET.DET
