# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.3
_src_path: https://github.com/epics-containers/services-template-helm
athena_services: []
cluster_name: argus
cluster_namespace: zsw36318
description: t02 IOC Instances and Services
git_platform: github.com
ioc_group: t02
location: bl01t
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
